# Generated by Django 5.2.3 on 2025-08-25 23:26

import camisas.fields
import camisas.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Costureira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('telefone', models.CharField(blank=True, max_length=40, null=True)),
                ('preco_corte_por_peca', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('preco_costura_por_peca', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('preco_correcao_por_peca', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=120)),
                ('razao_social', models.CharField(blank=True, max_length=180, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True)),
                ('ie', models.CharField(blank=True, max_length=30, null=True, verbose_name='Inscrição Estadual')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, max_length=30, null=True)),
                ('endereco', models.CharField(blank=True, max_length=180, null=True)),
                ('cidade', models.CharField(blank=True, max_length=80, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=camisas.models.logo_upload_to)),
            ],
            options={
                'ordering': ('nome_fantasia',),
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('action', models.CharField(choices=[('create', 'create'), ('update', 'update'), ('delete', 'delete'), ('approve_quote', 'approve_quote'), ('reject_quote', 'reject_quote'), ('login', 'login'), ('logout', 'logout')], max_length=32)),
                ('model', models.CharField(max_length=120)),
                ('object_id', models.CharField(max_length=64)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('path', models.CharField(blank=True, max_length=300, null=True)),
                ('method', models.CharField(blank=True, max_length=10, null=True)),
                ('ip', models.CharField(blank=True, max_length=45, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('cpf_cnpj', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, max_length=30, null=True)),
                ('endereco', models.CharField(blank=True, max_length=180, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='camisas.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categorias_despesa', to='camisas.empresa')),
            ],
            options={
                'verbose_name': 'Categoria de Despesa',
                'verbose_name_plural': 'Categorias de Despesa',
                'unique_together': {('empresa', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160)),
                ('cpf_cnpj', models.CharField(blank=True, max_length=20, null=True)),
                ('telefone', models.CharField(blank=True, max_length=40, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fornecedores', to='camisas.empresa')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
            },
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=240)),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('data_emissao', models.DateField(default=django.utils.timezone.localdate)),
                ('vencimento', models.DateField(blank=True, null=True)),
                ('forma_pagamento', models.CharField(choices=[('PIX', 'PIX'), ('BOLETO', 'Boleto'), ('CARTAO', 'Cartão'), ('TRANSF', 'Transferência'), ('DINH', 'Dinheiro'), ('OUTRO', 'Outro')], default='PIX', max_length=8)),
                ('status', models.CharField(choices=[('PEN', 'Pendente'), ('PAGA', 'Paga'), ('CANC', 'Cancelada')], default='PEN', max_length=4)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('anexo', models.FileField(blank=True, null=True, upload_to='despesas/%Y/%m')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despesas', to='camisas.categoriadespesa')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despesas', to='camisas.empresa')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='despesas', to='camisas.fornecedor')),
            ],
            options={
                'ordering': ('-data_emissao', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('unidade', models.CharField(choices=[('m', 'Metro'), ('un', 'Unidade'), ('kg', 'Quilo'), ('rolo', 'Rolo')], default='un', max_length=10)),
                ('estoque_atual', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('custo_medio', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('ativo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='insumos', to='camisas.categoriainsumo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='insumos', to='camisas.empresa')),
            ],
            options={
                'unique_together': {('empresa', 'nome', 'unidade')},
            },
        ),
        migrations.CreateModel(
            name='ParametrosEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('margem_lucro_padrao', models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=7)),
                ('acrescimo_padrao_percentual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7)),
                ('desconto_max_percentual', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=7)),
                ('impostos_percentual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7)),
                ('taxa_cartao_percentual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7)),
                ('custo_energia_mensal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('custo_internet_mensal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('outros_custos_fixos_mensais', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('custo_tinta_percentual', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7)),
                ('arredondar_para', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=7)),
                ('incluir_taxas_no_preco_base', models.BooleanField(default=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parametros', to='camisas.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('ORC', 'Orçamento'), ('PEN', 'Pendente'), ('PROD', 'Em Produção'), ('FAT', 'Faturado/Entregue'), ('CANC', 'Cancelado')], default='ORC', max_length=4)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('desconto_percentual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7)),
                ('acrescimo_percentual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7)),
                ('numero_orcamento', models.CharField(blank=True, max_length=40, null=True)),
                ('validade', models.DateField(blank=True, null=True)),
                ('condicoes', models.TextField(blank=True, null=True)),
                ('arte', camisas.fields.SafeImageField(blank=True, null=True, upload_to=camisas.models.arte_upload_to)),
                ('approval_token', models.CharField(db_index=True, default=camisas.models.gen_approval_token, editable=False, max_length=64, unique=True)),
                ('approval_status', models.CharField(choices=[('PEND', 'Pendente'), ('APRV', 'Aprovado'), ('REJ', 'Recusado')], default='PEND', max_length=4)),
                ('approval_decided_at', models.DateTimeField(blank=True, null=True)),
                ('approval_decision_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('approval_name', models.CharField(blank=True, max_length=120, null=True)),
                ('approval_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('approval_comment', models.TextField(blank=True, null=True)),
                ('approval_signature', camisas.fields.SafeImageField(blank=True, null=True, upload_to='assinaturas/%Y/%m')),
                ('approval_user_agent', models.TextField(blank=True, default='')),
                ('approval_timezone', models.CharField(blank=True, default='', max_length=64)),
                ('approval_hash', models.CharField(blank=True, default='', max_length=64)),
                ('artwork_token', models.CharField(db_index=True, default=camisas.models.gen_approval_token, editable=False, max_length=64, unique=True)),
                ('artwork_status', models.CharField(choices=[('PEND', 'Pendente'), ('APRV', 'Aprovado'), ('REJ', 'Recusado')], default='PEND', max_length=4)),
                ('artwork_decided_at', models.DateTimeField(blank=True, null=True)),
                ('artwork_decision_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('artwork_name', models.CharField(blank=True, max_length=120, null=True)),
                ('artwork_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('artwork_comment', models.TextField(blank=True, null=True)),
                ('artwork_signature', camisas.fields.SafeImageField(blank=True, null=True, upload_to='assinaturas/%Y/%m')),
                ('artwork_user_agent', models.TextField(blank=True, default='')),
                ('artwork_timezone', models.CharField(blank=True, default='', max_length=64)),
                ('artwork_hash', models.CharField(blank=True, default='', max_length=64)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='camisas.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='camisas.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='camisas.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Remessa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(db_index=True, default=camisas.models.gerar_numero_remessa, editable=False, max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('CORTE', 'Corte'), ('COSTURA', 'Costura'), ('CORRECAO', 'Correção')], max_length=10)),
                ('kg_enviados', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Se enviou tecido/peças por peso', max_digits=12)),
                ('enviado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('recebido_em', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ENVIADA', 'Enviada'), ('PARCIAL', 'Parcial'), ('CONCLUIDO', 'Concluído'), ('CANCELADA', 'Cancelada')], default='ENVIADA', max_length=12)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('costureira', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remessas', to='camisas.costureira')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remessas', to='camisas.empresa')),
                ('produto', models.ForeignKey(blank=True, help_text='(opcional) ajuda a agrupar variações', null=True, on_delete=django.db.models.deletion.PROTECT, to='camisas.produto')),
            ],
            options={
                'ordering': ('-enviado_em', '-id'),
            },
        ),
        migrations.CreateModel(
            name='PagamentoCostureira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago')], default='PENDENTE', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pago_em', models.DateTimeField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('costureira', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='camisas.costureira')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos_costureiras', to='camisas.empresa')),
                ('remessa', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pagamento', to='camisas.remessa')),
            ],
        ),
        migrations.CreateModel(
            name='VariacaoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho', models.CharField(max_length=10)),
                ('cor', models.CharField(default='Branco', max_length=40)),
                ('sku', models.CharField(blank=True, db_index=True, editable=False, max_length=40, unique=True)),
                ('estoque_atual', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('custo_unitario', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('preco_sugerido', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variacoes', to='camisas.produto')),
            ],
            options={
                'unique_together': {('produto', 'tamanho', 'cor')},
            },
        ),
        migrations.CreateModel(
            name='OrdemProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('custo_mao_de_obra', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('custo_indireto_rateado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens', to='camisas.empresa')),
                ('variacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='camisas.variacaoproduto')),
            ],
        ),
        migrations.CreateModel(
            name='MovimentoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('E', 'Entrada'), ('S', 'Saída')], max_length=1)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('quantidade', models.DecimalField(decimal_places=4, max_digits=12)),
                ('custo_unit', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('observacao', models.CharField(blank=True, max_length=160, null=True)),
                ('costureira', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='camisas.costureira')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='camisas.empresa')),
                ('insumo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='camisas.insumo')),
                ('remessa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='camisas.remessa')),
                ('variacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='camisas.variacaoproduto')),
            ],
            options={
                'ordering': ('-criado_em',),
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='camisas.pedido')),
                ('variacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='camisas.variacaoproduto')),
            ],
        ),
        migrations.CreateModel(
            name='ParcelaDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(default=1)),
                ('vencimento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('PEN', 'Pendente'), ('PAGA', 'Paga'), ('CANC', 'Cancelada')], default='PEN', max_length=4)),
                ('pago_em', models.DateTimeField(blank=True, null=True)),
                ('despesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='camisas.despesa')),
            ],
            options={
                'ordering': ('vencimento', 'numero'),
                'unique_together': {('despesa', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='RemessaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_prevista', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('qtd_ok', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('qtd_perda', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('qtd_extravio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('qtd_devolvida', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('preco_unit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Se vazio/zero, usa preço padrão da costureira para o tipo da remessa.', max_digits=10)),
                ('remessa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='camisas.remessa')),
                ('variacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_remessa', to='camisas.variacaoproduto')),
            ],
            options={
                'unique_together': {('remessa', 'variacao')},
            },
        ),
        migrations.CreateModel(
            name='FichaTecnicaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=4, max_digits=12)),
                ('fase', models.CharField(choices=[('AUTO', 'Automático (por categoria: tecido=corte; demais=costura)'), ('CORTE', 'Consumir na etapa de Corte'), ('COSTURA', 'Consumir na etapa de Costura')], default='AUTO', max_length=10)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='camisas.insumo')),
                ('variacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ficha', to='camisas.variacaoproduto')),
            ],
            options={
                'unique_together': {('variacao', 'insumo')},
            },
        ),
    ]
