# Generated by Django 5.2.3 on 2025-08-26 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camisas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('empresa', 'Empresa'), ('cliente', 'Cliente')], max_length=16)),
                ('signer_name', models.CharField(max_length=255)),
                ('signed_at', models.DateTimeField()),
                ('hash', models.CharField(db_index=True, max_length=128)),
                ('qr_data_url', models.TextField(blank=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esignatures', to='camisas.pedido')),
            ],
            options={
                'ordering': ['-signed_at'],
            },
        ),
    ]
