# Generated by Django 5.2.6 on 2025-09-19 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camisas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.CharField(blank=True, help_text='Ex: Sinal, Saldo final, Entrada', max_length=120, null=True)),
                ('forma', models.CharField(choices=[('PIX', 'Pix'), ('CRED', 'Cartão de Crédito'), ('DEB', 'Cartão de Débito'), ('DIN', 'Dinheiro')], default='PIX', max_length=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='camisas.pedido')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['data'],
            },
        ),
    ]
