# Generated by Django 5.2.6 on 2025-09-05 19:36

import camisas.fields
import camisas.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camisas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='anexo',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='despesas/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=camisas.models.logo_upload_to),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='arte',
            field=camisas.fields.SafeImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=camisas.models.arte_upload_to),
        ),
    ]
