# Generated by Django 5.2.6 on 2025-09-20 13:45

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camisas', '0002_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='arte',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagem'),
        ),
    ]
