# Generated by Django 5.2.3 on 2025-08-26 11:27

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camisas', '0002_esignature'),
    ]

    operations = [
        migrations.CreateModel(
            name='CotacaoConcorrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_nome', models.CharField(max_length=160)),
                ('cnpj', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, max_length=40, null=True)),
                ('validade', models.DateField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotacoes_concorrentes', to='camisas.pedido')),
            ],
            options={
                'ordering': ('-criado_em',),
            },
        ),
        migrations.CreateModel(
            name='CotacaoConcorrenteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('unidade', models.CharField(default='UN', max_length=10)),
                ('quantidade', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=10)),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('cotacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='camisas.cotacaoconcorrente')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
