# Generated by Django 5.2.6 on 2025-09-20 14:00

import camisas.fields
import camisas.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camisas', '0003_alter_empresa_logo_alter_pedido_arte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='arte',
            field=camisas.fields.SafeImageField(blank=True, null=True, upload_to=camisas.models.arte_upload_to),
        ),
    ]
