# Generated by Django 5.2.6 on 2025-09-23 13:43

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camisas', '0004_alter_pedido_arte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='arte',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='arte'),
        ),
        migrations.AlterField(
            model_name='personalizacaoitem',
            name='quantidade',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Quantidade opcional', null=True),
        ),
    ]
