# Generated by Django 5.2.6 on 2025-09-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camisas', '0005_alter_pedido_arte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='etapa_producao',
            field=models.CharField(choices=[('ARTE', 'Arte'), ('IMPRESSAO', 'Impressão'), ('ESTAMPAGEM', 'Estampagem'), ('ACABAMENTO', 'Acabamento'), ('QUALIDADE', 'Qualidade'), ('ENTREGA', 'Entrega')], db_index=True, default='ARTE', help_text='Etapa atual no fluxo de produção (Kanban).', max_length=20),
        ),
    ]
