# Generated by Django 5.2.6 on 2025-09-29 12:51

import camisas.fields
import camisas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camisas', '0006_pedido_etapa_producao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='logo',
            field=camisas.fields.SafeImageField(blank=True, null=True, upload_to=camisas.models.logo_upload_to),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='arte',
            field=camisas.fields.SafeImageField(blank=True, null=True, upload_to=camisas.models.arte_upload_to),
        ),
        migrations.AlterField(
            model_name='personalizacaoitem',
            name='tamanho_camisa',
            field=models.CharField(blank=True, choices=[('2A', '2 anos'), ('4A', '4 anos'), ('6A', '6 anos'), ('8A', '8 anos'), ('10A', '10 anos'), ('12A', '12 anos'), ('PP', 'PP'), ('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG'), ('XG', 'XG'), ('PP-BL', 'PP Baby Look'), ('P-BL', 'P Baby Look'), ('M-BL', 'M Baby Look'), ('G-BL', 'G Baby Look'), ('GG-BL', 'GG Baby Look'), ('XG-BL', 'XG Baby Look')], max_length=10, null=True),
        ),
    ]
