# Generated by Django 5.2.6 on 2025-09-30 21:52

import camisas.fields
import camisas.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camisas', '0009_alter_personalizacaoitem_tamanho_camisa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArteDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160)),
                ('descricao', models.TextField(blank=True, default='')),
                ('arquivo', camisas.fields.SafeImageField(blank=True, null=True, upload_to=camisas.models.arte_design_upload_to)),
                ('status', models.CharField(choices=[('PEND', 'Pendente'), ('WORK', 'Em criação'), ('WAIT', 'Aguardando cliente'), ('APRV', 'Aprovada'), ('REJ', 'Reprovada'), ('IMP', 'Para impressão')], db_index=True, default='PEND', max_length=4)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='artes', to='camisas.cliente')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artes', to='camisas.empresa')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artes', to='camisas.pedido')),
            ],
            options={
                'ordering': ('-criado_em',),
            },
        ),
    ]
