# Generated by Django 5.2.6 on 2025-09-30 22:36

import camisas.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camisas', '0010_artedesign'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artedesign',
            options={'ordering': ('criado_em', 'id')},
        ),
        migrations.AlterField(
            model_name='artedesign',
            name='arquivo',
            field=camisas.fields.SafeImageField(blank=True, null=True, upload_to='artes/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='artedesign',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='artes', to='camisas.cliente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artedesign',
            name='status',
            field=models.CharField(choices=[('PEND', 'Pendente'), ('WORK', 'Em criação'), ('WAIT', 'Aguardando'), ('APRV', 'Aprovada'), ('REJ', 'Reprovada'), ('IMP', 'Para impressão')], db_index=True, default='PEND', max_length=4),
        ),
    ]
