# Generated by Django 5.2.3 on 2025-08-27 11:36

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camisas', '0003_cotacaoconcorrente_cotacaoconcorrenteitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrcamentoExpress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('validade', models.DateField(blank=True, null=True)),
                ('cliente_nome', models.CharField(max_length=120)),
                ('cliente_whatsapp', models.CharField(help_text='Somente números. Ex: 63999999999', max_length=20)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado')], default='pendente', max_length=12)),
                ('aprovado_em', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('ativo', models.BooleanField(default=True)),
                ('jornada_diaria_min', models.PositiveIntegerField(default=480, help_text='Minutos/dia. Ex.: 480 = 8h')),
                ('almoco_min', models.PositiveIntegerField(default=120, help_text='Minutos de almoço. Ex.: 120 = 2h')),
                ('h_in_manha', models.TimeField(blank=True, null=True)),
                ('h_out_manha', models.TimeField(blank=True, null=True)),
                ('h_in_tarde', models.TimeField(blank=True, null=True)),
                ('h_out_tarde', models.TimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, help_text='Opcional: vincular a um usuário do sistema', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrcamentoExpressItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('unidade', models.CharField(blank=True, default='', max_length=16)),
                ('quantidade', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='camisas.orcamentoexpress')),
            ],
        ),
        migrations.CreateModel(
            name='FrequenciaDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('e1', models.TimeField(blank=True, null=True, verbose_name='Entrada manhã')),
                ('s1', models.TimeField(blank=True, null=True, verbose_name='Saída manhã')),
                ('e2', models.TimeField(blank=True, null=True, verbose_name='Entrada tarde')),
                ('s2', models.TimeField(blank=True, null=True, verbose_name='Saída tarde')),
                ('observacao', models.CharField(blank=True, default='', max_length=240)),
                ('minutos_previstos_override', models.PositiveIntegerField(blank=True, null=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencias', to='camisas.funcionario')),
            ],
            options={
                'ordering': ['-data'],
                'unique_together': {('funcionario', 'data')},
            },
        ),
    ]
