# Generated by Django 5.2.3 on 2025-08-28 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camisas', '0004_orcamentoexpress_funcionario_orcamentoexpressitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColetaPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo', models.CharField(choices=[('SIMPLES', 'Quantidades por tamanho'), ('NOMES', 'Tamanhos + nomes'), ('TIME', 'Time (nome + número + tamanho)')], default='SIMPLES', max_length=12)),
                ('token', models.CharField(db_index=True, max_length=40, unique=True)),
                ('expiracao', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('cliente_nome', models.CharField(blank=True, max_length=120, null=True)),
                ('cliente_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('obs_cliente', models.TextField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coletas', to='camisas.pedido')),
            ],
        ),
    ]
