# Generated by Django 5.2.3 on 2025-08-28 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camisas', '0005_coletapedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='orcamento_ocultar_total',
            field=models.BooleanField(default=False, help_text='Se marcado, esconde o bloco de totais e a coluna Subtotal no orçamento.'),
        ),
    ]
